
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "httpd-meta"
  labels:
    app: "httpd-meta"
data:
  DEBUG: "{{$.Values.DEBUG}}"
  ListenAddr: "{{$.Values.ListenHost}}:{{$.Values.ListenPort}}"



